version: '3.9'

services:
  front:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./:/home/node/front
      - /home/node/front/node_modules