export const appsData = [
  {
    expandible: null,
    id: '1',
    app_name: 'Atlassian',
    type: 'Productivity',
    installed_by: 'Sysadmin',
    user_group: 'Everyone',
    expense_period: parseFloat('499.00'),
  },
  {
    expandible: null,
    id: '2',
    app_name: 'Twitter',
    type: 'Social',
    installed_by: 'Sysadmin',
    user_group: 'Marketing',
    expense_period: parseFloat('499.00'),
  },
  {
    expandible: null,
    id: '3',
    app_name: 'Facebook',
    type: 'Social',
    installed_by: 'Sysadmin',
    user_group: 'Marketing',
    expense_period: parseFloat('499.00'),
  },
  {
    expandible: null,
    id: '4',
    app_name: 'Zoom',
    type: 'Productivity',
    installed_by: 'Sysadmin',
    user_group: 'Everyone',
    expense_period: parseFloat('499.00'),
  },
  {
    expandible: null,
    id: '5',
    app_name: 'YouTube',
    type: 'Social',
    installed_by: 'Sysadmin',
    user_group: 'Marketing',
    expense_period: parseFloat('499.00'),
  },
  {
    expandible: null,
    id: '6',
    app_name: 'Google Drive',
    type: 'Storage',
    installed_by: 'Sysadmin',
    user_group: 'Everyone',
    expense_period: parseFloat('499.00'),
  },
  {
    expandible: null,
    id: '7',
    app_name: 'Dropbox',
    type: 'Storage',
    installed_by: 'Sysadmin',
    user_group: 'Everyone',
    expense_period: parseFloat('499.00'),
  },
  {
    expandible: null,
    id: '8',
    app_name: 'We transfer',
    type: 'Storage',
    installed_by: 'Sysadmin',
    user_group: 'Desing',
    expense_period: parseFloat('499.00'),
  },
  {
    expandible: null,
    id: '8',
    app_name: 'Zillow',
    type: 'Real state',
    installed_by: 'Sysadmin',
    user_group: 'Sales',
    expense_period: parseFloat('499.00'),
  },
];
